### ISSUE TITLE
Move PHPUnit to require-dev

### ISSUE THREAD

**Issue by twhiston** [nuvoleweb/drupal-behat#11]
I see that your drupal-behat requires phpunit 5.5, but drupals core composer.json requires PHPUnit 4.8, which means that your module cannot be installed due to conflicts, how do you work around this?

**Comment by ademarco** [comment]
I guess we could move phpunit as a dev dependency, I'll try that as see how travis feels about it.

**Comment by ademarco** [comment]
Ok fixed and merged in `1.0.x`

**Comment by dnotes** [comment]
Hey, this is exactly my issue, but I still can't use the module. How does this help? Sorry to re-open.
