### ISSUE TITLE
Declaration of Drupal8::entityDelete() must be compatible with CoreInterface

### ISSUE THREAD

**Issue by sakiland** [nuvoleweb/drupal-behat#26]
I'm running Drupal 7 site. And whet try to run ./bin/behat command I'm getting following error

`Fatal error: Declaration of NuvoleWeb\Drupal\Driver\Cores\Drupal8::entityDelete() must be compatible with Drupal\Driver\Cores\CoreInterface::entityDelete($entity_type, $entity) in /var/www/html/sites/all/behat_test/vendor/nuvoleweb/drupal-behat/src/Driver/Cores/Drupal8.php on line 26`

Here's patch that fix this:
[entityDelete_must_be_compatible_with_CoreInterface.txt](https://github.com/nuvoleweb/drupal-behat/files/1544669/entityDelete_must_be_compatible_with_CoreInterface.txt)

**Comment by ptmkenny** [comment]
Any chance of getting a release that has this fix included?  I'm trying to get started with a Drupal 8 site and it seems like the latest official release doesn't include the fix.

**Comment by bircher** [comment]
Thank you for your contribution! It was merged to various branches.
