### ISSUE TITLE
Fatal error: Undefined method Drupal\Driver\Cores\Drupal8::getEntityIdByLabel()

### ISSUE THREAD

**Issue by jibla** [nuvoleweb/drupal-behat#28]
```php
Fatal error: Call to undefined method Drupal\Driver\Cores\Drupal8::getEntityIdByLabel()
```
I get above fatal error, when trying to execute, following step:
```behat
@Given I am editing the :type content :title
```

Versions I am working with, are following:
![image](https://user-images.githubusercontent.com/475343/36341137-0c0ba0c4-1403-11e8-869d-4280ac149aab.png)

Have anyone met, something like this?

**Comment by jibla** [comment]
It looks like, this (in [ContentContext](/nuvoleweb/drupal-behat/blob/1.x/src/DrupalExtension/Context/ContentContext.php#L73)):
```php
$this->getCore()
```
doesn't return object of [Drupal8](/nuvoleweb/drupal-behat/blob/1.x/src/Driver/Cores/Drupal8.php) class.

**Comment by jibla** [comment]
It was an issue with configuration. Closing.

**Comment by Nicasso** [comment]
@jibla Could you please share your solution? Because I'm having the same problem as you did.
