### ISSUE TITLE
Email Context not working.

### ISSUE THREAD

**Issue by omarlopesino** [nuvoleweb/drupal-behat#39]
Hi.

I am trying to use Email context but is not working.
For example, I receive the following error trying to check an email was sent:

```
    Then an email should be sent to "debug@example.com"
      No mail was sent. (Exception)
```

 Trying to check what is happening I saw a little mistake in [method get](https://github.com/nuvoleweb/drupal-behat/blob/5554a2492466d34e3d115990f250a0ccb91d5176/src/Driver/Objects/Drupal8/State.php#L18).

Working on a fast PR.

**Comment by omarlopesino** [comment]
Please review the PR, this solves the problem mentioned. Thanks!

**Comment by bircher** [comment]
Thank you for your contribution!
