### ISSUE TITLE
Disable access checking when querying for entities

### ISSUE THREAD

**Issue by carlosreig** [nuvoleweb/drupal-behat#49]
Hi,

I'm writing a tests and I want to create a translation for an entity. For doing this I have created the following step:

```
/**
   * Assert translation for given content.
   *
   * @param string $bundle
   *   The node type for which to add the translation.
   * @param string $title
   *   The title to identify the content by.
   * @param \Behat\Gherkin\Node\PyStringNode $string
   *   The text in yaml format that represents the translation.
   *
   * @Given the :entity_type translation for :bundle content :title:
   */
  public function assertTranslation($entity_type, $bundle, $title, TableNode $groupsTable) {

    foreach ($groupsTable->getHash() as $groupHash) {
      $entity = $groupHash;
      $entity['type'] = $bundle;

      Assert::keyExists($entity, 'langcode', __METHOD__ . ": Required field 'langcode' not found.");

      $id = $this->getDriver()->getCore()->getEntityIdByLabel($entity_type, $bundle, $title);
      $source = $this->getDriver()->getCore()->entityLoad($entity_type, $id);


      $this->getDriver()->getCore()->entityAddTranslation($source, $entity['langcode'], $entity);
    }

  }
```

It is based on src/DrupalExtension/Context/ContentContext.php:200 but it works with any entity types.

The problem I have is with the line `$this->getDriver()->getCore()->getEntityIdByLabel($entity_type, $bundle, $title);` because it is not returning anything even if the entity exists.

I have researched and I have figured out that the problem comes because the `\Drupal::entityQuery()` (used inside `getEntityIdByLabel`) is checking the access permissions to the entities.

I think this is not needed since we are in a "development environment" so I have created a patch in order to disable the access checking.

Thanks,
Carlos

**Comment by Sweetchuck** [comment]
I think this issue should be re-opened, because not every occurrences were fixed.

```
When I am deleting the "deleteme" term "Behat deleteme" 
NuvoleWeb\Drupal\DrupalExtension\Context\TaxonomyTermContext::iAmDeletingTheTerm()

Entity queries must explicitly set whether the query should be access checked or not.
See Drupal\Core\Entity\Query\QueryInterface::accessCheck(). (Drupal\Core\Entity\Query\QueryException)
```

\NuvoleWeb\Drupal\Driver\Cores\Drupal8::loadTaxonomyTermByName()
